runner: terraform

globals:
  stages:
    dev:
      vars:
        stage: dev
    staging:
      vars:
        stage: staging
    prod:
      vars:
        stage: prod

stacks:
  testStack:
    path: ./mocks/terraform/testStack
    local:
      path: ./data/terraform
    stages:
      __all__:
        vars:
          bucket_prefix: test
